Add a --linker-flags argument
Akuli/jou pull request #221
Opened 2023-02-13 18:21 UTC by Akuli

A bit annoying to use, but fixes #214 for now. Hopefully I will eventually create an actual package manager.

2023-02-13 18:22 UTC, Akuli commented on src/main.c
> +                // TODO: test
```suggestion
```

2023-02-13 18:22 UTC, Akuli commented on src/main.c
> +                // TODO: test
```suggestion
```

2023-02-14 01:04 UTC, taahol commented on examples/x11_window.jou
> +        x = XDrawImageString(display, window, gc, 50, 50, "hello", 5)
Variable `x` not needed.

2023-02-14 12:10 UTC, Akuli commented on examples/x11_window.jou
> +        x = XDrawImageString(display, window, gc, 50, 50, "hello", 5)
Related: #26

2023-02-17 11:36 UTC, littlewhitecloud commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
# Output: <jouexe>: --linker-flags cannot be given multiple times (try "<jouexe> --help")

2023-02-17 11:42 UTC, littlewhitecloud commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")

2023-02-17 11:43 UTC, littlewhitecloud requested changes

2023-02-17 11:43 UTC, littlewhitecloud commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
Should be:
```python
run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "<jouexe> --help")
```

2023-02-17 11:46 UTC, littlewhitecloud requested changes

2023-02-17 11:46 UTC, littlewhitecloud commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
Should be:
```python
run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "<jouexe> --help")
```

2023-02-17 11:46 UTC, littlewhitecloud commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
```suggestion
    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "<jouexe> --help")
```

2023-02-17 14:34 UTC, Akuli commented on tests/should_succeed/compiler_cli.jou
> +    run_jou("--linker-flags x --linker-flags y")  # Output: <jouexe>: --linker-flags cannot be given multiple times (try "./jou --help")
Thanks :)

2023-02-17 18:49 UTC, merged